version: "3.8"
services:
  yagi-server:
    build: .
    container_name: yagi-server
    ports:
      - 3333:3333
    environment:
      - DB_HOST=yagi-db
    volumes:
      - .:/usr/src/app
    depends_on:
      - yagi-db
    links:
      - yagi-db
    command: yarn dev

  yagi-db:
    image: postgres:12.5
    container_name: yagi-db
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
